"""Package-level acceptance (G007 T001 + T004): judge the BUILT wheel, not
the source tree.

The 0.3.1 gap this pins: ``[tool.hatch.build.targets.wheel]`` shipped
``orx/skills`` but not ``orx/agents``, so on a clean (non-editable)
install ``presets.source_agents_dir()`` fell back to a repo layout that
does not exist inside site-packages and ``orx preset install zcode``
reported every native role as "definition not packaged with this ORX
(install manually)". The regression here builds the wheel, installs it
into a throwaway venv, and proves — from OUTSIDE the repository — that:

- ``orx`` imports from the temporary site-packages (never the repo or an
  editable copy), with the probe's working directory outside the repo and
  a sanitized environment (no PYTHONPATH, isolated ORX_* layer);
- the three native ZCode role definitions (orx-worker, orx-verifier,
  orx-verifier-strong) ship in the wheel and install through the packaged
  preset with no "install manually" note, byte-identical to the packaged
  copies — the roles come from the installed package;
- the packaged default skills are present in the wheel the same way;
- the preset still never overwrites a live definition (a pre-existing
  custom orx-worker.md stays untouched; the missing roles still install):
  the update path for existing role files is explicit and documented in
  docs/upgrade-0.3.1.md, not a silent replacement.

T004 extends the same wheel install to the full release story (all via
the INSTALLED console script, never the source tree, and with no skip):

- the user layer through the CLI: preset install (fresh + preserve),
  EVERY packaged skill installed, one drifted and refreshed by
  ``orx skill update`` from the package;
- a local stand-in Goal outside the repo: init -> goal -> plan submit ->
  run parks host work (no paid model, no analytics, quota preflight off)
  -> claim -> heartbeat -> the legacy {summary, commands, artifacts}
  evidence shape REJECTED by name (exit 1, task untouched) -> the
  structured delivery result accepted -> an independent verdict via
  ``orx verify submit`` -> run done; --json envelopes and exit codes 0/1/2
  asserted throughout;
- the real v0.3.0 schema-v8 fixture (tests/fixtures/release-0.3.0,
  generated by the actual v0.3.0 code from the git tag — proven by
  regenerating and comparing normalized logical dumps): a copy is backed
  up (VACUUM INTO), upgraded to v11 by the installed new version, checked
  row-by-row across every pre-existing table and column, additive
  defaults verified (new tables empty, legacy nonces NULL), the REAL
  v0.3.0 read entry refuses the v11 file without modifying it, and the
  backup restores and reads back under the real v0.3.0 code. The source
  fixture stays byte-identical (sha256 asserted).

The build/install/probe mechanics live in ``scripts/check_release.py``
(one wheel build + one venv per module, shared by the tests here and by
the standalone release check). The fast source pin of the packaging
config itself is in tests/test_phase_c.py. The run book describing
entries, dependencies, fixture provenance and failure behavior is
docs/package-acceptance.md.
"""

from __future__ import annotations

import importlib.util
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent
FIXTURE_DIR = REPO_ROOT / "tests" / "fixtures" / "release-0.3.0"


def _load_check_release():
    spec = importlib.util.spec_from_file_location(
        "check_release", REPO_ROOT / "scripts" / "check_release.py"
    )
    module = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    spec.loader.exec_module(module)
    return module


check_release = _load_check_release()


@pytest.fixture(scope="module")
def installed(tmp_path_factory):
    """One wheel build + one clean venv install + one probe run, shared by
    every test in this module (the expensive part of the acceptance)."""
    workdir = tmp_path_factory.mktemp("orx-package-acceptance")
    wheel = check_release.build_wheel(workdir / "dist", REPO_ROOT)
    python = check_release.install_wheel(wheel, workdir / "venv")
    report = check_release.run_probe(python, workdir / "scratch")
    return {
        "workdir": workdir,
        "wheel": wheel,
        "python": python,
        "report": report,
    }


@pytest.fixture(scope="module")
def chain(installed):
    """The T004 sections, run once against the same wheel install: the CLI
    user-layer flow (preset + skills + the stand-in Goal) and the v0.3.0
    fixture chain (structure, upgrade, old-version rejection, backup
    restore, regeneration provenance)."""
    workdir = installed["workdir"]
    orx_bin = installed["python"].parent / "orx"
    cli = check_release.run_cli_flow(installed["python"], workdir / "cli-flow")
    structure, struct_problems = check_release.check_fixture_structure(
        FIXTURE_DIR, REPO_ROOT)
    upgrade = check_release.check_upgrade_chain(
        FIXTURE_DIR, installed["python"], orx_bin, workdir / "upgrade", REPO_ROOT)
    provenance = check_release.verify_fixture_provenance(
        FIXTURE_DIR, REPO_ROOT, installed["python"], workdir / "regen")
    return {
        "cli": cli,
        "structure": structure,
        "struct_problems": struct_problems,
        "upgrade": upgrade,
        "provenance": provenance,
    }


# ---------------------------------------------------------------------------
# Clean install: imports and resources come from the temporary package


def test_probe_ran_outside_the_repo_from_temp_site_packages(installed):
    report = installed["report"]
    # The probe's own working directory is the scratch dir (not the repo).
    assert not Path(report["probe_cwd"]).resolve().is_relative_to(REPO_ROOT)
    # orx itself imports from the throwaway venv's site-packages.
    assert report["orx_in_site_packages"]
    orx_file = Path(report["orx_file"])
    assert orx_file.is_relative_to(Path(report["site_packages"]))
    assert not orx_file.is_relative_to(REPO_ROOT)
    assert not installed["workdir"].is_relative_to(REPO_ROOT)


def test_wheel_ships_native_agent_definitions_and_default_skills(installed):
    report = installed["report"]
    assert report["agents_in_site_packages"], report["agents_source"]
    assert report["agents_present"] == {
        "orx-worker": True, "orx-verifier": True, "orx-verifier-strong": True,
    }
    assert report["skills_in_site_packages"], report["skills_source"]
    assert report["skills_present"] == {
        "orx-controller": True, "orx-agent": True,
    }


# ---------------------------------------------------------------------------
# The three roles install FROM THE PACKAGE through the preset


def test_clean_install_preset_installs_all_three_roles_from_the_package(installed):
    report = installed["report"]
    agents = report["preset_fresh"]["agents"]
    for name in check_release.NATIVE_AGENTS:
        row = agents[name]
        # Installed, and no "install manually" note — the 0.3.0 symptom.
        assert row["installed"] is True, (name, row)
        assert row["note"] is None, (name, row)
    # The installed files are byte-identical to the packaged copies: the
    # content provably came from the wheel, not from some repo fallback.
    assert report["preset_fresh"]["installed_contents_match_package"] == {
        "orx-worker": True,
        "orx-verifier": True,
        "orx-verifier-strong": True,
    }
    assert set(report["preset_fresh"]["profiles_added"]) == {
        "zcode-controller", "zcode-worker",
        "zcode-verifier-flash", "zcode-verifier-strong",
    }


def test_preset_from_the_package_preserves_existing_role_definitions(installed):
    """The preserve regression at package level: a live custom definition
    wins over the packaged one — the preset never silently replaces an
    existing role file (updates are explicit, per docs/upgrade-0.3.1.md)."""
    report = installed["report"]
    preserve = report["preset_preserve"]
    worker = preserve["agents"]["orx-worker"]
    assert worker["installed"] is False
    assert worker["preserved_existing"] is True
    assert preserve["custom_content_intact"] is True
    for name in ("orx-verifier", "orx-verifier-strong"):
        assert preserve["agents"][name]["installed"] is True


# ---------------------------------------------------------------------------
# The judging sections: empty problems on this workspace


def test_release_check_sections_report_no_problems(installed):
    report = installed["report"]
    problems = (
        check_release.check_package_resources(report)
        + check_release.check_preset_install(report)
    )
    assert problems == []


# ---------------------------------------------------------------------------
# T004: the user layer through the installed CLI (preset, every packaged
# skill, and the refresh path)


def test_cli_flow_reports_no_problems_and_wheel_version(chain, installed):
    cli = chain["cli"]
    assert cli["problems"] == []
    # The console script really is the wheel install's entry point.
    assert cli["orx_bin"] == str(installed["python"].parent / "orx")
    assert cli["orx_version"] == installed["report"]["orx_version"]


def test_cli_installs_preset_and_every_packaged_skill(chain):
    cli = chain["cli"]
    # Preset, fresh install: every native role from the package.
    rows = {row["name"]: row for row in cli["preset_fresh"]["agents"]}
    for name in check_release.NATIVE_AGENTS:
        assert rows[name]["installed"] is True
        assert rows[name].get("note") is None
    # Preserve case: a live custom definition wins, untouched.
    preserved = {row["name"]: row for row in cli["preset_preserve"]["agents"]}
    assert preserved["orx-worker"]["preserved_existing"] is True
    # Every packaged skill installs (the repo ships three).
    assert sorted(cli["packaged_skills"]) == [
        "orx-agent", "orx-controller", "orx-pbv",
    ]
    assert sorted(cli["skills"]["installed"]) == sorted(cli["packaged_skills"])
    # The canonical root and the symlinks stay inside the isolated HOME.
    home = Path(cli["skills"]["canonical_root"]).parent.parent
    assert Path(cli["skills"]["canonical_root"]).is_relative_to(home)
    for target in cli["skills"]["symlinked_into"]:
        assert Path(target).is_relative_to(home)
    # A drifted skill refreshes from the packaged copy, byte-identical.
    assert "orx-controller" in cli["skills"]["refreshed"]
    assert cli["skills"]["refresh_matches_package"] is True


# ---------------------------------------------------------------------------
# T004: the local stand-in Goal loop, outside the repo, through the
# installed CLI (planning, execution, structured delivery, verdict)


def test_stand_in_goal_loop_closes_with_structured_delivery(chain):
    standin = chain["cli"]["standin"]
    # Planning: one plan revision with two tasks; one active Goal throughout.
    assert standin["revision"] == 1 and standin["plan_tasks"] == 2
    assert standin["single_goal_after_plan"] is True
    assert standin["final_single_goal"] is True
    # Execution: host work is PARKED (no paid model, no analytics).
    assert standin["t001_parked"] == ["T001"]
    assert standin["heartbeat_sequence"] == 1
    # The legacy {summary, commands, artifacts} shape is rejected by name…
    rejection = standin["legacy_rejection"]
    assert rejection["exit_code"] == 1
    assert rejection["ok"] is False
    for token in ("evidence rejected", "'status'", "'checks'"):
        assert token in rejection["error"]
    # …and the rejection changed nothing: the task kept running.
    assert standin["t001_status_after_rejection"] == "running"
    # The structured delivery result is accepted, verified independently.
    assert standin["t001_after_complete"] == "verifying"
    assert standin["agent_entries"] == [check_release.STANDIN_AGENT_ENTRY]
    assert standin["t001_verdict_status"] == "passed"
    assert standin["t002_parked"] == ["T002"]
    assert standin["t002_after_complete"] == "passed"
    assert standin["final_run_status"] == "done"
    assert standin["final_task_statuses"] == {"T001": "passed", "T002": "passed"}
    # Exit codes: 1 for the rejected delivery, 2 for a click usage error.
    assert standin["usage_error_exit_code"] == 2


def test_stand_in_ran_outside_the_repo_and_every_json_step_enveloped(chain):
    steps = chain["cli"]["steps"]
    assert steps, "no CLI steps recorded"
    for step in steps:
        assert "--json" not in step["command"] or step.get("envelope") is not None, step
    standin_dir = Path(chain["cli"]["standin"]["project"])
    assert not standin_dir.resolve().is_relative_to(REPO_ROOT)


# ---------------------------------------------------------------------------
# T004: the real v0.3.0 schema-v8 fixture and its provenance


def test_fixture_is_a_genuine_non_trivial_v030_v8_sample(chain):
    structure = chain["structure"]
    assert chain["struct_problems"] == []
    assert structure["schema_version"] == 8
    # The v9+ tables and the v11 column do not exist yet in the sample.
    assert not set(check_release.V11_ADDITIVE_TABLES) & set(structure["tables"])
    # Core v8 tables carry real data (an empty fixture would prove nothing).
    for table in check_release.V8_CORE_TABLES:
        assert structure["tables"][table] > 0, table
    # The local tag still points at the provenance commit.
    assert structure["tag_commit"] == check_release.V030_COMMIT
    # The committed file is exactly what the real v0.3.0 code produces.
    assert chain["provenance"]["problems"] == []
    assert chain["provenance"]["matches_regeneration"] is True


# ---------------------------------------------------------------------------
# T004: the upgrade chain on a copy of the fixture (docs/upgrade-0.3.1.md §6)


def test_upgrade_preserves_every_v8_row_and_adds_only_defaults(chain):
    upgrade = chain["upgrade"]
    assert upgrade["problems"] == []
    assert upgrade["upgraded_schema_version"] == 11
    checked = upgrade["identity"]["tables_checked"]
    for table in check_release.V8_CORE_TABLES:
        assert table in checked, table
        assert checked[table]["rows"] > 0, table
        assert checked[table]["columns"] > 0, table
    # Row-by-row identity covered a meaningful slice of the sample.
    assert upgrade["identity"]["rows_compared"] >= 15
    # The in-flight task is still there, attempt rows intact.
    assert checked["attempts"]["rows"] >= 3


def test_real_v030_rejects_upgraded_db_and_backup_restores(chain):
    upgrade = chain["upgrade"]
    assert upgrade["problems"] == []
    # The read entry used for rejection really was the old version.
    assert upgrade["old_version_reported"] == "0.3.0"
    rejection = upgrade["old_rejection"]
    assert rejection["exit_code"] == 1
    assert "newer than supported version 8" in rejection["output_tail"]
    # The §6.1 backup exists, restores, and the old version reads it back.
    backup = next(s for s in upgrade["steps"]
                  if s["step"] == "backup-vacuum-into")
    assert backup["bytes"] > 0
    assert upgrade["restore"]["exit_code"] == 0
    assert upgrade["restore"]["goal_read_back"] is True
    # The source sample was never modified by any of it.
    sha = upgrade["source_sha256"]
    assert sha["before"] == sha["after"]
    assert sha["after"] == chain["structure"]["sha256"]
