"""End-to-end stand-in acceptance of the G006 host-progress machinery.

Two continuous stories replay docs/host-progress-contract.md §10 (the frozen
recovery boundaries) with local stand-ins — dispatch calls double for the
worker and the Controller, a frozen ORX clock replaces every wait, so no paid
model runs and nothing really sleeps:

(a) claim -> explicit reports -> overdue CHECK HINT -> `orx run` recovery
    re-surface -> the ORIGINAL attempt's valid late delivery is accepted:
    the hint observed, it never acted;
(b) confirmed death -> explicit fail/retry -> a fresh report window -> the
    old attempt's late report AND late delivery are both rejected, its
    reports live on only as timeline history.

A final section pins the documentation to the machinery (contract §11):
README and both skills teach the explicit report discipline and the
bounded-wait / check-the-original-session-first rule without promoting the
channel as an automatic heartbeat, a liveness proof, or an automatic
recovery.
"""

from __future__ import annotations

from datetime import datetime, timedelta, timezone
from pathlib import Path

import pytest

from orx import dispatch
from orx.records import ConflictError

from conftest import (
    HOST_CONFIG_TOML,
    active_task,
    ir_for,
    make_project,
    task_spec,
    write_evidence,
)

REPO_ROOT = Path(__file__).resolve().parent.parent

# A 1-minute report threshold so the overdue transition is a small, exact
# clock move (the comparison itself is contract §8: age >= timeout, closed).
PROGRESS_TIMEOUT_ONE_MIN = HOST_CONFIG_TOML.replace(
    '[worker]\nprofiles = ["host-worker", "host-external"]\n',
    '[worker]\nprofiles = ["host-worker", "host-external"]\n'
    "progress_timeout_min = 1\n",
)


def _freeze_orx_clock(monkeypatch):
    """Freeze both ORX clock seams (write and read side) at one instant."""
    holder = {"now": datetime(2026, 10, 6, 12, 0, 0, tzinfo=timezone.utc)}

    def now():
        return holder["now"].isoformat(timespec="microseconds")

    monkeypatch.setattr("orx.state.now", now)
    monkeypatch.setattr("orx.dispatch.db_now", now)
    return holder


@pytest.fixture
def e2e(tmp_path, monkeypatch):
    """A parked host task under a frozen ORX clock and a 1-minute report
    threshold. Yields (project, clock): advance clock["now"] instead of
    sleeping — every threshold comparison is arithmetic on the seam."""
    monkeypatch.chdir(tmp_path)
    clock = _freeze_orx_clock(monkeypatch)
    project = make_project(tmp_path, config_toml=PROGRESS_TIMEOUT_ONE_MIN)
    goal = dispatch.create_goal(
        project, objective="e2e progress acceptance",
        acceptance=["the stand-in loop closes safely"],
        constraints=[], context="",
    )[0]
    dispatch.submit_plan(project, ir_for(goal, [
        task_spec("T001", acceptance=goal.acceptance, verification=["true"]),
    ]))
    dispatch.run_slice(project)
    yield project, clock
    project.close()


def _progress_of(project, task_id="T001"):
    """The current-window progress block the task list publishes."""
    row = next(t for t in dispatch.task_list(project) if t["id"] == task_id)
    return row["progress"]


def _recovery_of(project, task_id="T001"):
    """The `orx run` recovery face for one running task."""
    return next(e for e in dispatch.run_slice(project)["recovery"]
                if e["task"] == task_id)


def _report_events(project, task_id="T001"):
    return [e for e in dispatch.timeline(project, task_id=task_id)["entries"]
            if e["event"] == "attempt.report"]


# ---------------------------------------------------------------------------
# Scenario (a): reports, overdue hint, recovery re-surface, and the ORIGINAL
# attempt's valid late delivery still accepted (§10 bullet 2-3)


def test_scenario_a_overdue_hint_then_original_attempt_late_delivery(e2e, tmp_path):
    project, clock = e2e

    # The worker claims (session-bound so the hint can name its handle) and
    # works the assignment.
    claimed = dispatch.task_claim(project, "T001", session="sess-worker-a")
    attempt_id = claimed["attempt"]

    # Explicit progress reports at key phases (contract §2/§5): each response
    # names the attempt, a per-attempt sequence, and received_at generated by
    # the frozen ORX clock — never a client timestamp.
    first = dispatch.task_heartbeat(
        project, "T001", attempt_id, "exploring", "repo walked, plan holds",
    )
    assert first == {
        "task": "T001",
        "attempt": attempt_id,
        "sequence": 1,
        "phase": "exploring",
        "message": "repo walked, plan holds",
        "received_at": clock["now"].isoformat(timespec="microseconds"),
    }
    clock["now"] = clock["now"] + timedelta(seconds=20)
    second = dispatch.task_heartbeat(
        project, "T001", attempt_id, "checking", "round 1/3 red, fixing",
    )
    assert second["sequence"] == 2

    # The current window is fresh: reported, aged against the frozen clock.
    fresh = _progress_of(project)
    assert fresh["attempt"] == attempt_id
    assert fresh["state"] == "reported"
    assert fresh["phase"] == "checking"
    assert fresh["message"] == "round 1/3 red, fixing"
    assert fresh["age_sec"] == 0
    assert fresh["timeout_sec"] == 60  # configured 1 minute, in seconds
    assert fresh["hint"] is None and fresh["note"] is None

    # Long silence: age crosses the threshold and the window turns overdue.
    clock["now"] = clock["now"] + timedelta(seconds=90)
    attempts_before = len(project.store.attempts_all())
    events_before = len(project.store.task_events_all())

    recovery = _recovery_of(project)
    assert recovery["attempt"] == attempt_id
    assert recovery["session_ref"] == "sess-worker-a"
    progress = recovery["progress"]
    assert progress["attempt"] == attempt_id
    assert progress["state"] == "overdue"
    assert progress["phase"] == "checking"
    assert progress["age_sec"] == 90
    assert progress["timeout_sec"] == 60
    # The hint only advises: check the ORIGINAL session before any fail/retry.
    assert ">= 1m threshold" in progress["hint"]
    assert "check the original worker session" in progress["hint"]
    assert "handle: sess-worker-a" in progress["hint"]
    assert "before any fail/retry" in progress["hint"]
    # The recovery contract still binds late results to the attempt and keeps
    # the fail/retry door explicitly human.
    assert f"orx task complete T001 --attempt {attempt_id}" in recovery["contract"]
    assert "orx task fail T001" in recovery["contract"]
    assert "orx task retry T001" in recovery["contract"]

    # The overdue hint is observation only: nothing moved anywhere. Still
    # running, no new attempt, no extra task event, no second worker.
    assert active_task(project, "T001").status == "running"
    assert len(project.store.attempts_all()) == attempts_before
    assert len(project.store.task_events_all()) == events_before
    # The same overdue window rides status and the timeline's current block.
    assert dispatch.status_data(project)["tasks"][0]["progress"] == progress
    timeline = dispatch.timeline(project, task_id="T001")
    [current] = timeline["current"]
    assert current == {"task": "T001", "progress": progress}
    # Both reports are append-only history carrying the full identity.
    assert [e["detail"] for e in _report_events(project)] == [
        f"worker T001 a{attempt_id} #1 exploring — repo walked, plan holds",
        f"worker T001 a{attempt_id} #2 checking — round 1/3 red, fixing",
    ]

    # The ORIGINAL attempt's valid late delivery is accepted — overdue never
    # invalidated it. The completion passes its own gate ('true').
    result = dispatch.task_complete(
        project, "T001", str(write_evidence(tmp_path, "late.json")),
        attempt_id=attempt_id,
    )
    assert result["status"] == "passed"
    assert result["attempt"] == attempt_id
    assert dispatch.status_data(project)["run"]["status"] == "done"

    # The delivered attempt stays closed: one more report from it is refused
    # before any ownership question (the task is no longer running) — a
    # report never revives a delivered attempt — and the two recorded
    # reports survive as queryable history bound to it.
    late_report = _heartbeat_rejection(project, attempt_id)
    assert late_report.reason == "task_not_running"
    stored = project.store.attempt_progress_all(attempt_id)
    assert [r.sequence for r in stored] == [1, 2]
    assert len(_report_events(project)) == 2


def _heartbeat_rejection(project, attempt_id):
    """Run one heartbeat for a (dead) attempt and return the raised error so
    the story can pin the machine reason (contract §5) alongside the type."""
    with pytest.raises(ConflictError) as excinfo:
        dispatch.task_heartbeat(
            project, "T001", attempt_id, "checking", "late text",
        )
    return excinfo.value


# ---------------------------------------------------------------------------
# Scenario (b): confirmed death -> explicit fail/retry -> fresh window -> the
# old attempt's late report AND delivery both rejected (§10 bullet 4)


def test_scenario_b_confirmed_death_fail_retry_rejects_old_attempt(e2e, tmp_path):
    project, clock = e2e

    # Round 1 runs and reports, then goes overdue — the same observation as
    # scenario (a), compressed: the hint is the CHECK cue, not a verdict.
    claimed = dispatch.task_claim(project, "T001", session="sess-worker-b")
    old_attempt = claimed["attempt"]
    dispatch.task_heartbeat(
        project, "T001", old_attempt, "implementing", "mid-refactor",
    )
    clock["now"] = clock["now"] + timedelta(seconds=4000)
    overdue = _recovery_of(project)
    assert overdue["attempt"] == old_attempt
    assert overdue["progress"]["state"] == "overdue"
    assert "check the original worker session" in overdue["progress"]["hint"]

    # Death is confirmed by the human (the Controller here), never by ORX:
    # the explicit fail closes the attempt, the retry reopens the task.
    dispatch.task_fail(project, "T001", "original session confirmed dead")
    dispatch.task_retry(project, "T001")

    # A fresh round is parked (host_required, not recovery) and claimed —
    # a NEW attempt owns the task; the old one can never win it back.
    parked = [e for e in dispatch.run_slice(project)["host_required"]
              if e["task"] == "T001"]
    assert len(parked) == 1
    new_claim = dispatch.task_claim(project, "T001", session="sess-worker-b2")
    new_attempt = new_claim["attempt"]
    assert new_attempt != old_attempt

    # The new report window starts unknown: the old attempt's report never
    # fills it, on any face.
    window = _progress_of(project)
    assert window["attempt"] == new_attempt
    assert window["state"] == "unknown"
    assert window["phase"] is None and window["message"] is None
    assert window["received_at"] is None
    assert window["hint"] is None
    assert dispatch.status_data(project)["tasks"][0]["progress"] == window
    assert next(c["progress"] for c in
                dispatch.timeline(project)["current"]
                if c["task"] == "T001") == window

    # The OLD attempt's late report is rejected (closed attempt), while the
    # new attempt reports freely with its own sequence numbering.
    old_report = _heartbeat_rejection(project, old_attempt)
    assert old_report.reason == "attempt_closed"
    accepted = dispatch.task_heartbeat(
        project, "T001", new_attempt, "checking", "fresh window",
    )
    assert accepted["sequence"] == 1  # per-attempt sequences never carry over
    assert _progress_of(project) == {
        "attempt": new_attempt,
        "state": "reported",
        "phase": "checking",
        "message": "fresh window",
        "received_at": accepted["received_at"],
        "age_sec": 0,
        "timeout_sec": 60,
        "hint": None,
        "note": None,
    }

    # The OLD attempt's late delivery is rejected as stale: the retry moved
    # ownership, and no delivery from the closed attempt may close the task.
    with pytest.raises(ConflictError, match="stale"):
        dispatch.task_complete(
            project, "T001", str(write_evidence(tmp_path, "stale.json")),
            attempt_id=old_attempt,
        )
    assert active_task(project, "T001").status == "running"

    # The old attempt's report survives only as timeline history — never as
    # the current window, which shows the NEW attempt's report.
    events = _report_events(project)
    assert [e["detail"] for e in events] == [
        f"worker T001 a{old_attempt} #1 implementing — mid-refactor",
        f"worker T001 a{new_attempt} #1 checking — fresh window",
    ]
    current = next(c["progress"] for c in
                   dispatch.timeline(project)["current"]
                   if c["task"] == "T001")
    assert current["attempt"] == new_attempt
    assert current["state"] == "reported"
    assert current["phase"] == "checking"

    # The new attempt delivers normally and closes the loop.
    result = dispatch.task_complete(
        project, "T001", str(write_evidence(tmp_path, "round2.json")),
        attempt_id=new_attempt,
    )
    assert result["status"] == "passed"
    assert result["attempt"] == new_attempt
    assert dispatch.status_data(project)["run"]["status"] == "done"
    # History intact after the pass: both attempts' reports stay queryable.
    assert [r.sequence for r in project.store.attempt_progress_all(old_attempt)] == [1]
    assert [r.sequence for r in project.store.attempt_progress_all(new_attempt)] == [1]
    assert len(_report_events(project)) == 2


# ---------------------------------------------------------------------------
# The documentation teaches the contract §11 discipline (and stays inside it)


def _skill(name: str) -> str:
    return (REPO_ROOT / "skills" / name / "SKILL.md").read_text()


def _flat(text: str) -> str:
    """Whitespace-flattened copy: phrase assertions must survive the line
    wrapping the documents happen to use."""
    return " ".join(text.split())


def test_readme_teaches_explicit_reports_without_promising_more():
    text = _flat((REPO_ROOT / "README.md").read_text())
    # The command surface and the current-window/threshold semantics…
    assert "orx task heartbeat" in text
    assert "--attempt" in text and "--phase" in text
    assert "unknown" in text and "reported" in text and "overdue" in text
    assert "worker.progress_timeout_min" in text
    assert "default 60" in text  # the builtin default, stated as minutes
    # …the recovery boundaries (late delivery accepted; fail/retry resets)…
    assert "stays acceptable however stale the report is" in text
    assert "attempt_closed" in text and "attempt_superseded" in text
    # …and the honest non-claims: explicit calls, no timer, no liveness proof.
    assert "no automatic heartbeat" in text
    assert "not a liveness proof" in text


def test_worker_skill_teaches_explicit_reports_at_key_phases():
    text = _flat(_skill("orx-agent"))
    assert "orx task heartbeat" in text
    assert "--attempt" in text and "--phase" in text
    # Report timing is explicit and tied to key phases of the assignment…
    assert "report progress explicitly at key phases" in text
    # …and the skill never sells the channel as more than it is.
    assert "no automatic heartbeat" in text
    assert "not proof your process is alive" in text
    assert "never evidence for acceptance" in text


def test_controller_skill_teaches_bounded_wait_and_check_original_first():
    text = _flat(_skill("orx-controller"))
    assert "orx task heartbeat" in text       # it knows the worker channel
    assert "progress" in text                 # the recovery window field
    assert "timeout_sec" in text              # the window's threshold field
    assert "worker.progress_timeout_min" in text
    # The §10 discipline: bounded wait, check the ORIGINAL session first,
    # fail/retry only on a death the human confirmed.
    assert "bounded" in text
    assert "check the original worker session before any fail/retry" in text
    assert "confirmed dead" in text
    # Observation is not verdict: the hint acts on nothing by itself.
    assert "not a liveness proof" in text
    assert "no automatic heartbeat" in text
    assert "the hint acts on nothing by itself" in text
    assert "still accepted" in text  # the late delivery survives staleness


def _negated(line_lower: str, phrase: str) -> bool:
    """True when every occurrence of phrase on the line is preceded by a
    negation (no/not/never) — a disclaimer, not a promotion."""
    index = line_lower.find(phrase)
    while index != -1:
        prefix = line_lower[:index].rstrip()
        if not prefix.endswith(("no", "not", "never")):
            return False
        index = line_lower.find(phrase, index + 1)
    return True


def test_no_doc_line_about_heartbeat_claims_savings_or_automation():
    """Contract §11 red lines, applied where they bind: no line mentioning
    the report channel may claim token/time savings, an automatic heartbeat,
    or a lease/keepalive. (The README's replan section legitimately mentions
    that an earlier token-savings claim was WITHDRAWN — a disclaimer about a
    different feature that never mentions the report channel.)"""
    for path in (
        REPO_ROOT / "README.md",
        REPO_ROOT / "skills" / "orx-agent" / "SKILL.md",
        REPO_ROOT / "skills" / "orx-controller" / "SKILL.md",
    ):
        for line in path.read_text().splitlines():
            if "heartbeat" not in line.lower():
                continue
            lower = line.lower()
            assert "token" not in lower, (path, line)
            assert "saving" not in lower, (path, line)
            assert _negated(lower, "automatic heartbeat"), (path, line)
            assert _negated(lower, "keepalive"), (path, line)
            assert _negated(lower, "lease"), (path, line)
